version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
     - 9000:3000
    volumes:
     - ./nginx.conf:/etc/nginx/conf.d/default.conf
     - ./app/:/usr/share/nginx/html/
    command: /bin/bash -c "nginx -g 'daemon off;'"